export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
];

export const translations = {
  en: {
    title: 'AgroGuard AI',
    subtitle: 'Agricultural Assistant',
    placeholder: 'Ask about crops, pests, diseases, farming tips...',
    send: 'Send',
    uploadImage: 'Upload Image',
    analyzing: 'Thinking...',
    welcome: '🌱 Hello! I\'m AgroGuard AI Assistant. I can help you with:\n\n🐛 Pest identification and control\n🌿 Disease management\n🌾 Crop advice and farming tips\n🌦️ Seasonal guidance\n🚜 Equipment recommendations\n\nWhat agricultural question can I help you with today?',
    dragDrop: 'Drag and drop an image here, or click to select',
    supportedFormats: 'Supports JPG, PNG, WebP',
    startVoice: 'Start voice input',
    stopVoice: 'Stop voice input',
    clearChat: 'Clear chat',
    closeChat: 'Close chat',
    testBackend: 'Test backend',
    poweredBy: 'Powered by AgroGuard AI • Press Enter to send',
    chatCleared: '🌱 Chat cleared! How can I help you with your agricultural questions?',
    errorMessage: '🚨 I apologize, but I\'m having trouble right now. Please try again in a moment, or contact support if the issue persists.'
  },
  es: {
    title: 'AgroGuard AI',
    subtitle: 'Asistente Agrícola',
    placeholder: 'Pregunta sobre cultivos, plagas, enfermedades, consejos agrícolas...',
    send: 'Enviar',
    uploadImage: 'Subir Imagen',
    analyzing: 'Pensando...',
    welcome: '🌱 ¡Hola! Soy el Asistente AgroGuard AI. Puedo ayudarte con:\n\n🐛 Identificación y control de plagas\n🌿 Manejo de enfermedades\n🌾 Consejos de cultivos y agricultura\n🌦️ Orientación estacional\n🚜 Recomendaciones de equipos\n\n¿Con qué pregunta agrícola puedo ayudarte hoy?',
    dragDrop: 'Arrastra y suelta una imagen aquí, o haz clic para seleccionar',
    supportedFormats: 'Soporta JPG, PNG, WebP',
    startVoice: 'Iniciar entrada de voz',
    stopVoice: 'Detener entrada de voz',
    clearChat: 'Limpiar chat',
    closeChat: 'Cerrar chat',
    testBackend: 'Probar backend',
    poweredBy: 'Desarrollado por AgroGuard AI • Presiona Enter para enviar',
    chatCleared: '🌱 ¡Chat limpiado! ¿Cómo puedo ayudarte con tus preguntas agrícolas?',
    errorMessage: '🚨 Me disculpo, pero estoy teniendo problemas ahora mismo. Por favor intenta de nuevo en un momento, o contacta soporte si el problema persiste.'
  },
  fr: {
    title: 'AgroGuard AI',
    subtitle: 'Assistant Agricole',
    placeholder: 'Demandez sur les cultures, ravageurs, maladies, conseils agricoles...',
    send: 'Envoyer',
    uploadImage: 'Télécharger Image',
    analyzing: 'Réflexion...',
    welcome: '🌱 Bonjour! Je suis l\'Assistant AgroGuard AI. Je peux vous aider avec:\n\n🐛 Identification et contrôle des ravageurs\n🌿 Gestion des maladies\n🌾 Conseils de cultures et d\'agriculture\n🌦️ Orientation saisonnière\n🚜 Recommandations d\'équipement\n\nQuelle question agricole puis-je vous aider aujourd\'hui?',
    dragDrop: 'Glissez-déposez une image ici, ou cliquez pour sélectionner',
    supportedFormats: 'Supporte JPG, PNG, WebP',
    startVoice: 'Démarrer la saisie vocale',
    stopVoice: 'Arrêter la saisie vocale',
    clearChat: 'Effacer le chat',
    closeChat: 'Fermer le chat',
    testBackend: 'Tester le backend',
    poweredBy: 'Alimenté par AgroGuard AI • Appuyez sur Entrée pour envoyer',
    chatCleared: '🌱 Chat effacé! Comment puis-je vous aider avec vos questions agricoles?',
    errorMessage: '🚨 Je m\'excuse, mais j\'ai des difficultés en ce moment. Veuillez réessayer dans un moment, ou contactez le support si le problème persiste.'
  },
  hi: {
    title: 'AgroGuard AI',
    subtitle: 'कृषि सहायक',
    placeholder: 'फसलों, कीटों, बीमारियों, खेती की युक्तियों के बारे में पूछें...',
    send: 'भेजें',
    uploadImage: 'छवि अपलोड करें',
    analyzing: 'सोच रहा हूं...',
    welcome: '🌱 नमस्ते! मैं AgroGuard AI सहायक हूं। मैं आपकी मदद कर सकता हूं:\n\n🐛 कीट पहचान और नियंत्रण\n🌿 रोग प्रबंधन\n🌾 फसल सलाह और खेती की युक्तियां\n🌦️ मौसमी मार्गदर्शन\n🚜 उपकरण सिफारिशें\n\nआज मैं आपके किस कृषि प्रश्न में मदद कर सकता हूं?',
    dragDrop: 'यहां एक छवि खींचें और छोड़ें, या चुनने के लिए क्लिक करें',
    supportedFormats: 'JPG, PNG, WebP समर्थित',
    startVoice: 'आवाज इनपुट शुरू करें',
    stopVoice: 'आवाज इनपुट बंद करें',
    clearChat: 'चैट साफ करें',
    closeChat: 'चैट बंद करें',
    testBackend: 'बैकएंड परीक्षण',
    poweredBy: 'AgroGuard AI द्वारा संचालित • भेजने के लिए Enter दबाएं',
    chatCleared: '🌱 चैट साफ हो गई! मैं आपके कृषि प्रश्नों में कैसे मदद कर सकता हूं?',
    errorMessage: '🚨 मुझे खुशी है, लेकिन मुझे अभी परेशानी हो रही है। कृपया एक क्षण में फिर से कोशिश करें, या यदि समस्या बनी रहती है तो सहायता से संपर्क करें।'
  },
  zh: {
    title: 'AgroGuard AI',
    subtitle: '农业助手',
    placeholder: '询问作物、害虫、疾病、农业技巧...',
    send: '发送',
    uploadImage: '上传图片',
    analyzing: '思考中...',
    welcome: '🌱 您好！我是AgroGuard AI助手。我可以帮助您：\n\n🐛 害虫识别和控制\n🌿 疾病管理\n🌾 作物建议和农业技巧\n🌦️ 季节性指导\n🚜 设备推荐\n\n今天我可以帮助您解决什么农业问题？',
    dragDrop: '将图片拖放到此处，或点击选择',
    supportedFormats: '支持 JPG、PNG、WebP',
    startVoice: '开始语音输入',
    stopVoice: '停止语音输入',
    clearChat: '清除聊天',
    closeChat: '关闭聊天',
    testBackend: '测试后端',
    poweredBy: '由AgroGuard AI提供支持 • 按Enter发送',
    chatCleared: '🌱 聊天已清除！我如何帮助您解决农业问题？',
    errorMessage: '🚨 很抱歉，我现在遇到了问题。请稍后再试，如果问题仍然存在，请联系支持。'
  },
};